---
kind: pipeline
type: docker
name: verify
steps:
- name: install
  image: danlynn/ember-cli:3.24.0
  commands:
  - npm ci
- name: test
  image: danlynn/ember-cli:3.24.0
  commands:
    - npm run test:ember
- name: test-compat
  image: danlynn/ember-cli:3.24.0
  failure: ignore
  commands:
    - npm run test:ember-compatibility
trigger:
  event:
    - push

---
kind: pipeline
type: docker
name: release
steps:
- name: npm-release
  image: plugins/npm
  settings:
    token:
      from_secret: npm_access_token
trigger:
  event:
    - tag
